import os

from key_recovery import darkside_recover, nested_recover, mfkey32_recover
from crypto1 import Crypto1, prng_successor, odd_parity8


def _simulate_darkside_nack(uid: int, key: bytes, sector: int, nr_ar: bytes):
    """Simulate card behavior: return True if parity matches (NACK)."""
    c = Crypto1(key)
    block = sector * 4
    # Simulate auth: card generates nonce, we skip full auth
    # For testing, just check if the recovery algorithms work with synthetic data
    # The actual NACK detection depends on the full crypto1 protocol
    pass  # Complex simulation -- tested via integration


def test_nested_recover_known_key():
    """Test nested recovery with synthetic nonce pairs."""
    from key_recovery import find_prng_distance, _bswap32

    # find_prng_distance expects wire-order (big-endian) inputs.
    # Generate values: pick internal-order start, advance PRNG, byte-swap to wire.
    nt_internal = 0x01020304
    nt_target_internal = prng_successor(nt_internal, 200)
    nt_wire = _bswap32(nt_internal)
    nt_target_wire = _bswap32(nt_target_internal)

    dist = find_prng_distance(nt_wire, nt_target_wire, max_dist=1000)
    assert dist == 200


def test_find_prng_distance():
    from key_recovery import find_prng_distance, _bswap32
    # Internal-order values, then byte-swap to wire order for the function
    nt_internal = 0xAABBCCDD
    target_internal = prng_successor(nt_internal, 42)
    assert find_prng_distance(_bswap32(nt_internal), _bswap32(target_internal), 100) == 42


def test_find_prng_distance_not_found():
    from key_recovery import find_prng_distance
    assert find_prng_distance(0x11111111, 0x22222222, 10) is None


def test_mfkey32_recover():
    """Test mfkey32 subprocess recovery with known test vectors."""
    from key_recovery import _MFKEY32_PATH
    if not os.path.isfile(_MFKEY32_PATH):
        import pytest
        pytest.skip("mfkey32.exe not built")

    # Test vectors generated by gen_test.c with key a0a1a2a3a4a5
    uid = 0xE413B3DA
    auth_data = [
        {"nt": 0x11223344, "nr": 0x49F4A0BB, "ar": 0x3365D352},
        {"nt": 0x55667788, "nr": 0x1D627CD2, "ar": 0x82F513EE},
    ]
    keys = mfkey32_recover(uid, auth_data)
    assert len(keys) == 1
    assert keys[0] == bytes.fromhex("a0a1a2a3a4a5")


def test_mfkey32_recover_insufficient_data():
    """mfkey32_recover returns empty with fewer than 2 exchanges."""
    keys = mfkey32_recover(0xDEADBEEF, [{"nt": 1, "nr": 2, "ar": 3}])
    assert keys == []


def test_calibrate_nested_distance():
    """Calibration finds correct PRNG distance using known key."""
    from key_recovery import calibrate_nested_distance, _bswap32

    uid_wire = 0xE413B3DA
    known_key = bytes.fromhex("FFFFFFFFFFFF")
    nt_known_wire = 0x01020304
    dist = 160

    # Generate encrypted nonce in internal order (matching Python crypto1)
    uid_le = _bswap32(uid_wire)
    nt_known_le = _bswap32(nt_known_wire)
    nt_pred = prng_successor(nt_known_le, dist)
    c = Crypto1(known_key)
    ks32 = c.crypto1_word(uid_le ^ nt_pred, 0)
    nt_target_enc_le = nt_pred ^ ks32
    # Convert encrypted nonce back to wire order for the function
    nt_target_enc_wire = _bswap32(nt_target_enc_le)

    result = calibrate_nested_distance(uid_wire, nt_known_wire, nt_target_enc_wire, known_key)
    assert result == dist


def test_calibrate_nested_distance_not_found():
    """Calibration returns None when no valid distance exists."""
    from key_recovery import calibrate_nested_distance

    result = calibrate_nested_distance(0xDEADBEEF, 0x11111111, 0x22222222,
                                       bytes.fromhex("FFFFFFFFFFFF"))
    assert result is None


def test_nested_recover_with_exe():
    """Nested recovery via subprocess finds the correct key."""
    from key_recovery import _NESTED_PATH

    if not os.path.isfile(_NESTED_PATH):
        import pytest
        pytest.skip("nested.exe not built")

    uid = 0xE413B3DA
    dist = 160

    # Wire-order test vectors generated by C crapto1 gen_nested_test.exe
    # with key=A0A1A2A3A4A5, uid=E413B3DA, dist=160
    nonce_pairs = [
        (0x01020304, 0x63D9D799),
        (0xAABBCCDD, 0x2191633B),
        (0x11223344, 0x22F3EF32),
        (0x55667788, 0x5C288AD1),
        (0xDEADBEEF, 0x9C052720),
    ]

    keys = nested_recover(uid, dist, nonce_pairs)
    assert len(keys) == 1
    assert keys[0] == bytes.fromhex("a0a1a2a3a4a5")
