import os

from key_recovery import darkside_recover, nested_recover, mfkey32_recover
from crypto1 import Crypto1, prng_successor, odd_parity8


def _simulate_darkside_nack(uid: int, key: bytes, sector: int, nr_ar: bytes):
    """Simulate card behavior: return True if parity matches (NACK)."""
    c = Crypto1(key)
    block = sector * 4
    # Simulate auth: card generates nonce, we skip full auth
    # For testing, just check if the recovery algorithms work with synthetic data
    # The actual NACK detection depends on the full crypto1 protocol
    pass  # Complex simulation -- tested via integration


def test_nested_recover_known_key():
    """Test nested recovery with synthetic nonce pairs."""
    # This test verifies the algorithm can find a key when given
    # correctly generated nonce pairs.
    # Full integration test requires firmware + card.
    uid = 0xE413B3DA
    known_key = bytes.fromhex("FFFFFFFFFFFF")
    target_key = bytes.fromhex("A0A1A2A3A4A5")

    # Generate synthetic nonce pair
    # In real attack: nt_known comes from auth, nt_target from nested auth
    # The relationship: nt_target = prng_successor(nt_known, ticks)
    nt_known = 0x01020304
    # Target nonce after ~200 PRNG ticks (typical auth delay)
    nt_target_plain = prng_successor(nt_known, 200)

    # The encrypted nt_target would require full crypto simulation
    # For unit test, verify the PRNG distance calculation works
    from key_recovery import find_prng_distance
    dist = find_prng_distance(nt_known, nt_target_plain, max_dist=1000)
    assert dist == 200


def test_find_prng_distance():
    from key_recovery import find_prng_distance
    nt = 0xAABBCCDD
    target = prng_successor(nt, 42)
    assert find_prng_distance(nt, target, 100) == 42


def test_find_prng_distance_not_found():
    from key_recovery import find_prng_distance
    assert find_prng_distance(0x11111111, 0x22222222, 10) is None


def test_mfkey32_recover():
    """Test mfkey32 subprocess recovery with known test vectors."""
    from key_recovery import _MFKEY32_PATH
    if not os.path.isfile(_MFKEY32_PATH):
        import pytest
        pytest.skip("mfkey32.exe not built")

    # Test vectors generated by gen_test.c with key a0a1a2a3a4a5
    uid = 0xE413B3DA
    auth_data = [
        {"nt": 0x11223344, "nr": 0x49F4A0BB, "ar": 0x3365D352},
        {"nt": 0x55667788, "nr": 0x1D627CD2, "ar": 0x82F513EE},
    ]
    keys = mfkey32_recover(uid, auth_data)
    assert len(keys) == 1
    assert keys[0] == bytes.fromhex("a0a1a2a3a4a5")


def test_mfkey32_recover_insufficient_data():
    """mfkey32_recover returns empty with fewer than 2 exchanges."""
    keys = mfkey32_recover(0xDEADBEEF, [{"nt": 1, "nr": 2, "ar": 3}])
    assert keys == []
