esphome:
  name: ir-blaster
  friendly_name: IR Blaster

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "IR-Blaster Fallback"
    password: !secret fallback_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: GPIO5
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all
  tolerance: 25%
  idle: 25ms

# Example buttons — replace with learned codes from your remotes
button:
  - platform: template
    name: "TV Power"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4040
          command: 0x12BF
  - platform: template
    name: "TV Volume Up"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4040
          command: 0x1AB5
