esphome:
  name: ir-blaster
  friendly_name: IR Blaster

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "IR-Blaster Fallback"
    password: "ir-blaster-fallback"

captive_portal:

web_server:
  port: 80

logger:

api:
  encryption:
    key: !secret api_key
  services:
    - service: send_ir_nec
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_nec:
            address: !lambda 'return address;'
            command: !lambda 'return command;'

    - service: send_ir_samsung
      variables:
        data: int
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return data;'

    - service: send_ir_sony
      variables:
        data: int
        nbits: int
      then:
        - remote_transmitter.transmit_sony:
            data: !lambda 'return data;'
            nbits: !lambda 'return nbits;'

    - service: send_ir_rc5
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_rc5:
            address: !lambda 'return address;'
            command: !lambda 'return command;'

    - service: send_ir_rc6
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_rc6:
            address: !lambda 'return address;'
            command: !lambda 'return command;'

    - service: send_ir_raw
      variables:
        code: int[]
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38000
            code: !lambda 'return code;'

    - service: send_ir_pronto
      variables:
        data: string
      then:
        - remote_transmitter.transmit_pronto:
            data: !lambda 'return data;'

ota:
  - platform: esphome
    password: !secret ota_password

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 33%
  non_blocking: false

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all
  tolerance: 25%
  idle: 25ms

status_led:
  pin: GPIO2

# Samsung TV power — captured raw Pronto from remote
button:
  - platform: template
    name: "Samsung TV Power"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 000D 0000 002E 002F 000F 0017 000F 0024 000F 005D 000F 0024 000F 0017 000F 003B 000F 0046 0010 005C 0010 0016 0010 005C 0010 002E 0010 03C2"

# Camera remote — NEC protocol, address 0xDB34
  # Preset positions
  - platform: template
    name: "Camera Preset 1"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xFE01
  - platform: template
    name: "Camera Preset 2"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xFD02
  - platform: template
    name: "Camera Preset 3"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xFC03
  - platform: template
    name: "Camera Preset 4"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xFB04
  - platform: template
    name: "Camera Preset 5"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xFA05
  - platform: template
    name: "Camera Preset 6"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xF906
  # Pan controls — send initial NEC frame, then proper NEC repeat codes
  # NEC repeat code = 9ms burst + 2.25ms space + 562us stop (signals "button held")
  - platform: template
    name: "Camera Pan Up"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xEE11
      - delay: 40ms
      - repeat:
          count: 15
          then:
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38000
                code: [9000, -2250, 562]
            - delay: 98ms
  - platform: template
    name: "Camera Pan Down"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xEB14
      - delay: 40ms
      - repeat:
          count: 15
          then:
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38000
                code: [9000, -2250, 562]
            - delay: 98ms
  - platform: template
    name: "Camera Pan Right"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xED12
      - delay: 40ms
      - repeat:
          count: 15
          then:
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38000
                code: [9000, -2250, 562]
            - delay: 98ms
  - platform: template
    name: "Camera Pan Left"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xEC13
      - delay: 40ms
      - repeat:
          count: 15
          then:
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38000
                code: [9000, -2250, 562]
            - delay: 98ms
  # Auto tracking
  - platform: template
    name: "Camera Auto Track On"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xE51A
  - platform: template
    name: "Camera Auto Track Off"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xDB34
          command: 0xE31C
