#!/usr/bin/env python3
"""ESP32-WROOM-32 ESPHome node: schematic layout script (kicad-schematic DSL).

Single-sided SMD board, copper etched on the xTool F1 Ultra fiber laser.
USB-C -> CH340C (3.3 V mode) -> ESP32, AMS1117-3.3 regulator, EN/BOOT buttons
with auto-reset, full GPIO breakout, I2C header with pull-ups, 1-Wire header
with pull-up, power + user LEDs.

Project symbols (esp32node.kicad_sym, generated by make_symbols.py):
  U1 esp32node:ESP32-WROOM-32_Phys -- pins in module order, so the J2/J3
     breakout wires straight across.
  U3 esp32node:CH340C_3V3 -- V3 typed power_in for the 3.3 V supply mode.

Run:  python3 esp32node_sch.py esp32node.kicad_sch
"""
import sys
from pathlib import Path
sys.path.insert(0, "/home/mads/.claude/skills/kicad-schematic/scripts")
from schdraw import Sheet

HERE = Path(__file__).resolve().parent
G = lambda n: round(n * 1.27, 2)

FP_R   = "Resistor_SMD:R_0805_2012Metric"
FP_C   = "Capacitor_SMD:C_0805_2012Metric"
FP_LED = "LED_SMD:LED_0805_2012Metric"
FP_SW  = "Button_Switch_SMD:SW_SPST_PTS645Sx43SMTR92"
FP_Q   = "Package_TO_SOT_SMD:SOT-23"
FP_U3  = "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm"
FP_U2  = "Package_TO_SOT_SMD:SOT-223-3_TabPin2"
FP_U1  = "esp32node:ESP32-WROOM-32_NoVias"  # stock footprint minus the 0.2 mm thermal vias
FP_J1  = "Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal"
FP_H16 = "Connector_PinHeader_2.54mm:PinHeader_1x16_P2.54mm_Vertical"
FP_H4  = "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical"
FP_H3  = "Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical"

# project_file: inherit the root-sheet uuid the .kicad_pro already records,
# otherwise every re-emit mints a new one and Eeschema drops the symbols out
# of connectivity. lib_dirs: finds esp32node.kicad_sym beside this script.
sh = Sheet(paper="A3", title="ESP32 node", project="esp32node",
           project_file=str(HERE / "esp32node.kicad_pro"), lib_dirs=[str(HERE)])

def R(ref, at, val, rot=0):  return sh.place("Device:R", ref, at=at, rot=rot, value=val, footprint=FP_R)
def C(ref, at, val, rot=0):  return sh.place("Device:C", ref, at=at, rot=rot, value=val, footprint=FP_C)
def top(part):   # (top_pin, bottom_pin) of a two-pin vertical part
    a, b = part.pin(1), part.pin(2)
    return (a, b) if a.y < b.y else (b, a)
def run(a, b, lab_x=None, text=None, rot=0):
    """Horizontal wire a->b, split at lab_x where a net label sits (a label
    lands on a wire END, never mid-span)."""
    if text is None:
        sh.seg(a, b); return
    m = (lab_x, a.y if hasattr(a, "y") else a[1])
    sh.seg(a, m); sh.seg(m, b); sh.label(m, text, rot=rot)

# ============================================================ band 1: power
sh.note((G(80), G(18)), "3.3 V regulator  (USB 5 V -> AMS1117-3.3 -> 3V3)", size=2)
u2 = sh.place("Regulator_Linear:AMS1117-3.3", "U2", at=(G(100), G(30)), value="AMS1117-3.3", footprint=FP_U2)
vi, vo, ug = u2.pin("VI"), u2.pin("VO"), u2.pin("GND")
sh.seg(vi, (G(84), vi.y)); sh.rail((G(84), vi.y), net="+5V")
c1 = C("C1", (G(88), G(33)), "10u"); sh.seg(top(c1)[0], top(c1)[0])
sh.seg(vo, (G(116), vo.y)); sh.rail((G(116), vo.y), net="+3V3")
c2 = C("C2", (G(112), G(33)), "10u")
RAIL1 = G(40)
for p in (top(c1)[1], ug, top(c2)[1]):
    sh.seg(p, (p.x, RAIL1))
sh.seg((G(88), RAIL1), (G(112), RAIL1)); sh.gnd((G(100), RAIL1))
# power LED
r7 = R("R7", (G(130), G(28)), "1k"); sh.rail(top(r7)[0], net="+3V3")
d1 = sh.place("Device:LED", "D1", at=(G(130), G(36)), rot=90, value="LED red (power)", footprint=FP_LED)
da, dk = (d1.pin("A"), d1.pin("K"))
assert da.y < dk.y, "LED anode should be on top"
sh.seg(top(r7)[1], da); sh.gnd(dk)
# PWR_FLAGs
sh.power("power:+5V", (G(150), G(26))); sh.seg((G(150), G(26)), (G(150), G(28))); sh.seg((G(150), G(28)), (G(154), G(28)))
sh.power("power:PWR_FLAG", (G(154), G(28)))
sh.power("power:GND", (G(162), G(28))); sh.seg((G(162), G(28)), (G(166), G(28)))
sh.power("power:PWR_FLAG", (G(166), G(28)))

# ============================================================ band 2: USB-C
sh.note((G(26), G(92)), "USB-C input  (5 V + USB 2.0 data, CC pull-downs for C-to-C cables)", size=2)
j1 = sh.place("Connector:USB_C_Receptacle_USB2.0_16P", "J1", at=(G(36), G(112)), value="USB-C", footprint=FP_J1)
j1.field_at = {"Reference": (G(30), G(96)), "Value": (G(36), G(96))}
vb = j1.pin("A4"); sh.rail(vb, net="+5V")
cc1, cc2 = j1.pin("A5"), j1.pin("B5")
sh.seg(cc1, (G(72), cc1.y)); r1 = R("R1", (G(72), G(107)), "5.1k"); assert top(r1)[0].xy == (G(72), cc1.y)
r1.field_at = {"Reference": (r1.x + 3.8, cc1.y - 3.81), "Value": (r1.x + 3.8, cc1.y - 1.27)}
sh.seg(cc2, (G(64), cc2.y)); r2 = R("R2", (G(64), G(109)), "5.1k"); assert top(r2)[0].xy == (G(64), cc2.y)
dm_a, dm_b = j1.pin("A7"), j1.pin("B7")       # D-
dp_a, dp_b = j1.pin("A6"), j1.pin("B6")       # D+
sh.seg(dm_a, dm_b); sh.seg(dm_b, (G(52), dm_b.y)); sh.label((G(52), dm_b.y), "USB_D-")
sh.seg(dp_a, dp_b); sh.seg(dp_b, (G(52), dp_b.y)); sh.label((G(52), dp_b.y), "USB_D+")
sh.nc(j1.pin("A8"), j1.pin("B8"))
RAIL2 = G(134)
jg, jsh = j1.pin("A1"), j1.pin("SH")
for p in (jg, jsh, top(r1)[1], top(r2)[1]):
    sh.seg(p, (p.x, RAIL2))
sh.seg((jsh.x, RAIL2), (G(72), RAIL2)); sh.gnd((G(52), RAIL2))

# ============================================================ band 2: CH340C
sh.note((G(78), G(88)), "USB-UART bridge  (CH340C, no crystal)", size=2)
u3 = sh.place("esp32node:CH340C_3V3", "U3", at=(G(92), G(112)), value="CH340C", footprint=FP_U3)
udp, udm = u3.pin("UD+"), u3.pin("UD-")
sh.seg(udp, (G(78), udp.y)); sh.label((G(78), udp.y), "USB_D+", rot=180)
sh.seg(udm, (G(78), udm.y)); sh.label((G(78), udm.y), "USB_D-", rot=180)
sh.nc(u3.pin("R232"), u3.pin(7), u3.pin(8), u3.pin("~{CTS}"), u3.pin("~{DSR}"), u3.pin("~{RI}"), u3.pin("~{DCD}"))
u3.field_at = {"Reference": (G(98), G(123)), "Value": (G(98), G(125))}
vcc, v3, u3g = u3.pin("VCC"), u3.pin("V3"), u3.pin("GND")
# 3.3 V mode per the CH340 datasheet: V3 tied to VCC, both on +3V3, so TXD
# and DTR/RTS swing 3.3 V into the ESP32 (which is not 5 V tolerant).
VT = G(96)
c7 = C("C7", (G(78), G(99)), "100n"); assert top(c7)[0].xy == (G(78), VT); sh.gnd(top(c7)[1])
c5 = C("C5", (G(112), G(99)), "100n"); assert top(c5)[0].xy == (G(112), VT); sh.gnd(top(c5)[1])
sh.seg(vcc, (vcc.x, VT)); sh.seg(v3, (v3.x, VT))
for xa, xb in ((G(78), G(84)), (G(84), vcc.x), (vcc.x, v3.x), (v3.x, G(112))):
    sh.seg((xa, VT), (xb, VT))
sh.rail((G(84), VT), net="+3V3")
sh.gnd(u3g)
txd, rxd = u3.pin("TXD"), u3.pin("RXD")
sh.seg(txd, (G(102), txd.y)); sh.label((G(102), txd.y), "RXD0")
sh.seg(rxd, (G(102), rxd.y)); sh.label((G(102), rxd.y), "TXD0")
dtr, rts = u3.pin("~{DTR}"), u3.pin("~{RTS}")

# ============================================================ band 2: auto-reset + EN/IO0
sh.note((G(104), G(148)), "Reset / boot  (esptool auto-reset: DTR/RTS -> EN/IO0, RESET + BOOT buttons)", size=2)
XR = G(104)                                  # RTS riser
r3 = R("R3", (G(110), dtr.y), "10k", rot=90)
run(dtr, r3.pin(1), G(102), "DTR")
q1 = sh.place("Transistor_BJT:Q_NPN_BEC", "Q1", at=(G(120), dtr.y), value="S8050", footprint=FP_Q)
sh.seg(r3.pin(2), q1.pin("B"))
q1c, q1e = q1.pin("C"), q1.pin("E"); assert q1c.y < q1e.y
Y2 = G(132)
YE = q1e.y + G(2)                            # Q1 emitter -> RTS riser
run(rts, (XR, rts.y), G(102), "RTS")
sh.seg((XR, rts.y), (XR, YE)); sh.seg((XR, YE), (XR, Y2))
sh.seg(q1e, (q1e.x, YE)); sh.seg((q1e.x, YE), (XR, YE))
r4 = R("R4", (G(110), Y2), "10k", rot=90); sh.seg((XR, Y2), r4.pin(1))
q2 = sh.place("Transistor_BJT:Q_NPN_BEC", "Q2", at=(G(120), Y2), value="S8050", footprint=FP_Q)
sh.seg(r4.pin(2), q2.pin("B"))
q2c, q2e = q2.pin("C"), q2.pin("E")
sh.seg(q2e, (q2e.x, q2e.y + G(2))); sh.seg((q2e.x, q2e.y + G(2)), (G(126), q2e.y + G(2)))
sh.label((G(126), q2e.y + G(2)), "DTR")
# EN node: Q1 collector, 10k pull-up, 1u delay cap, RESET button
YEN = G(108)
sh.seg(q1c, (q1c.x, YEN))
r5 = R("R5", (G(132), YEN - G(3)), "10k"); assert top(r5)[1].xy == (G(132), YEN); sh.rail(top(r5)[0], net="+3V3")
c6 = C("C6", (G(138), YEN + G(3)), "1u"); assert top(c6)[0].xy == (G(138), YEN); sh.gnd(top(c6)[1])
sw1 = sh.place("Switch:SW_Push", "SW1", at=(G(148), YEN + G(4)), rot=90, value="RESET", footprint=FP_SW)
s1t, s1b = top(sw1); assert s1t.xy == (G(148), YEN), s1t.xy; sh.gnd(s1b)
for xa, xb in ((q1c.x, G(132)), (G(132), G(138)), (G(138), G(148)), (G(148), G(154))):
    sh.seg((xa, YEN), (xb, YEN))
sh.label((G(154), YEN), "EN")
# IO0 node: Q2 collector, 10k pull-up, BOOT button
YB = q2c.y
r6 = R("R6", (G(132), YB - G(3)), "10k"); assert top(r6)[1].xy == (G(132), YB); sh.rail(top(r6)[0], net="+3V3")
sw2 = sh.place("Switch:SW_Push", "SW2", at=(G(148), YB + G(4)), rot=90, value="BOOT", footprint=FP_SW)
s2t, s2b = top(sw2); assert s2t.xy == (G(148), YB); sh.gnd(s2b)
for xa, xb in ((q2c.x, G(132)), (G(132), G(148)), (G(148), G(154))):
    sh.seg((xa, YB), (xb, YB))
sh.label((G(154), YB), "IO0")

# ============================================================ band 2: ESP32 + GPIO breakout
sh.note((G(170), G(72)), "ESP32-WROOM-32 + GPIO breakout  (J2 / J3 in module pin order)", size=2)
UX, UY = G(216), G(112)
u1 = sh.place("esp32node:ESP32-WROOM-32_Phys", "U1", at=(UX, UY), value="ESP32-WROOM-32", footprint=FP_U1)
slot = lambda k: round(UY - 20.32 + 2.54 * k, 2)
assert u1.pin(2).xy == (UX - 15.24, slot(0)) and u1.pin(38).xy == (UX + 15.24, slot(0)), (u1.pin(2).xy, u1.pin(38).xy)
HX_L, HX_R = UX - 15.24 - G(24), UX + 15.24 + G(24)        # header pin columns
j2 = sh.place("Connector_Generic:Conn_01x16", "J2", at=(HX_L - 5.08, slot(0) + 17.78), mirror="y", value="GPIO L", footprint=FP_H16)
j3 = sh.place("Connector_Generic:Conn_01x16", "J3", at=(HX_R + 5.08, slot(0) + 17.78), value="GPIO R", footprint=FP_H16)
u1.field_at = {"Reference": (UX - G(5), UY - G(19)), "Value": (UX + G(4), UY - G(19))}
for j in (j2, j3):
    j.field_at = {"Reference": (j.x, slot(0) - G(4)), "Value": (j.x, slot(15) + G(4))}
for k in range(16):
    assert j2.pin(k + 1).xy == (HX_L, slot(k)), (k, j2.pin(k + 1).xy)
    assert j3.pin(k + 1).xy == (HX_R, slot(k)), (k, j3.pin(k + 1).xy)
LAB_L, LAB_R = HX_L + G(8), HX_R - G(8)
# left: J2 pin k+1 <-> module pin LEFT[k]
LEFT  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, None, 1]
LNAME = [None, "EN", "SVP", "SVN", "IO34", "IO35", "IO32", "IO33", "IO25", "IO26", "IO27", "IO14", "IO12", "IO13", None, None]
for k, (mp, nm) in enumerate(zip(LEFT, LNAME)):
    if mp is None or k in (0, 15):
        continue
    run(j2.pin(k + 1), u1.pin(mp), LAB_L, nm)
# +3V3 row: tap up to the decoupling rail (C3 100n, C4 10u) above the bundle
XT, YR = UX - 15.24 - G(4), slot(0) - G(16)
sh.seg(j2.pin(1), (XT, slot(0))); sh.seg((XT, slot(0)), u1.pin(2)); sh.seg((XT, slot(0)), (XT, YR))
c3 = C("C3", (XT - G(6), YR + G(3)), "100n"); c4 = C("C4", (XT - G(14), YR + G(3)), "10u")
for c in (c3, c4):
    assert top(c)[0].y == YR; sh.gnd(top(c)[1])
sh.seg((XT, YR), (c3.x, YR)); sh.seg((c3.x, YR), (c4.x, YR)); sh.rail((XT, YR), net="+3V3")
# J2.15 = +5V: squeezed between two wired rows, so the port lies on its side
sh.seg(j2.pin(15), (HX_L + G(4), slot(14))); p5 = sh.power("power:+5V", (HX_L + G(4), slot(14)), rot=270)
p5.field_at = {"Value": (HX_L + G(9), slot(14))}
# GND row (J2.16 <-> module pin 1)
sh.seg(j2.pin(16), (LAB_L, slot(15))); sh.seg((LAB_L, slot(15)), u1.pin(1)); sh.gnd((LAB_L, slot(15)))
# right: J3 pin k+1 <-> module pin RIGHT[k]
RIGHT = [38, 37, 36, 35, 34, 33, 31, 30, 29, 28, 27, 26, 25, 24, 23, 39]
RNAME = [None, "IO23", "IO22", "TXD0", "RXD0", "IO21", "IO19", "IO18", "IO5", "IO17", "IO16", "IO4", "IO0", "IO2", "IO15", None]
for k, (mp, nm) in enumerate(zip(RIGHT, RNAME)):
    if nm is None:
        continue
    run(u1.pin(mp), j3.pin(k + 1), LAB_R, nm)
# GND rows: top row hooks up and over to its ground symbol, bottom row drops
XG = LAB_R
sh.seg(u1.pin(38), (XG, slot(0))); sh.seg((XG, slot(0)), j3.pin(1))
sh.seg((XG, slot(0)), (XG, slot(0) - G(6))); sh.seg((XG, slot(0) - G(6)), (XG + G(2), slot(0) - G(6)))
sh.gnd((XG + G(2), slot(0) - G(6)), drop=0)
sh.seg(u1.pin(39), (XG, slot(15))); sh.seg((XG, slot(15)), j3.pin(16)); sh.gnd((XG, slot(15)))
# flash pins + NC along the bottom edge: never connected on a WROOM
sh.nc(*[u1.pin(n) for n in (17, 18, 19, 20, 21, 22, 32)])

# ============================================================ band 3: peripherals
sh.note((G(130), G(168)), "User LED (IO2)", size=2)
Y3 = G(178)
sh.seg((G(140), Y3), (G(146), Y3)); sh.label((G(140), Y3), "IO2", rot=180)
r8 = R("R8", (G(149), Y3), "1k", rot=90); assert r8.pin(1).xy == (G(146), Y3)
d2 = sh.place("Device:LED", "D2", at=(G(156), Y3 + G(3)), rot=90, value="LED blue", footprint=FP_LED)
sh.seg(r8.pin(2), d2.pin("A")); sh.gnd(d2.pin("K"))

sh.note((G(168), G(168)), "I2C  (SDA IO23, SCL IO22, 4k7)", size=2)
j4 = sh.place("Connector_Generic:Conn_01x04", "J4", at=(G(200), G(180)), value="I2C", footprint=FP_H4)
p1, p2, p3, p4 = (j4.pin(i) for i in (1, 2, 3, 4))
V3X, V3TOP = G(188), G(172)
sh.seg(p1, (V3X, p1.y)); sh.seg((V3X, p1.y), (V3X, V3TOP)); sh.power("power:+3V3", (V3X, V3TOP))
# SDA on IO23, not IO21: on the single-layer board J3 runs IO23, IO22, TXD0,
# RXD0, IO21 in that order, and IO21+IO22 into one header would trap the UART
# pair (a forced crossing). IO23/IO22 sit side by side on J3. Decided 2026-09-25.
sh.seg(p2, (G(182), p2.y)); sh.label((G(182), p2.y), "IO23", rot=180)
r9 = R("R9", (G(184), p2.y - G(3)), "4.7k"); assert top(r9)[1].xy == (G(184), p2.y)
sh.seg(p3, (G(170), p3.y)); sh.label((G(170), p3.y), "IO22", rot=180)
r10 = R("R10", (G(174), p3.y - G(3)), "4.7k"); assert top(r10)[1].xy == (G(174), p3.y)
PU = G(174)
sh.seg(top(r10)[0], (G(174), PU)); sh.seg((G(174), PU), (V3X, PU)); sh.seg(top(r9)[0], (G(184), PU))
sh.seg(p4, (G(192), p4.y)); sh.gnd((G(192), p4.y))
for r in (r9, r10):
    r.field_at = {"Reference": (r.x - 4.3, r.y - 2.54), "Value": (r.x - 4.3, r.y)}

sh.note((G(216), G(168)), "1-Wire header (DS18B20 pinout: GND, DQ, 3V3)", size=2)
j5 = sh.place("Connector_Generic:Conn_01x03", "J5", at=(G(236), G(180)), mirror="x", value="1-Wire", footprint=FP_H3)
g5, dq, v5 = (j5.pin(i) for i in (1, 2, 3))
assert g5.y > dq.y > v5.y, (g5.y, dq.y, v5.y)
sh.seg(v5, (G(226), v5.y)); sh.seg((G(226), v5.y), (G(226), V3TOP)); sh.power("power:+3V3", (G(226), V3TOP))
sh.seg(dq, (G(218), dq.y)); sh.label((G(218), dq.y), "IO4", rot=180)
r11 = R("R11", (G(222), dq.y - G(3)), "4.7k"); assert top(r11)[1].xy == (G(222), dq.y)
sh.seg(top(r11)[0], (G(226), top(r11)[0].y))
sh.seg(g5, (G(230), g5.y)); sh.gnd((G(230), g5.y))
r11.field_at = {"Reference": (r11.x - 4.3, r11.y - 2.54), "Value": (r11.x - 4.3, r11.y)}

# ============================================================ target netlist
T = {}
def net(name, *pins):
    T.setdefault(name, set()).update(pins)
net("+5V", ("J1","A4"),("J1","A9"),("J1","B4"),("J1","B9"),("U2","3"),("C1","1"),("J2","15"))
net("+3V3", ("U2","2"),("C2","1"),("R7","1"),("U1","2"),("C3","1"),("C4","1"),("R5","1"),("R6","1"),("J2","1"),
    ("U3","16"),("U3","4"),("C7","1"),("C5","1"),
    ("J4","1"),("R9","1"),("R10","1"),("J5","3"),("R11","1"))
net("GND", ("J1","A1"),("J1","A12"),("J1","B1"),("J1","B12"),("J1","SH"),("R1","2"),("R2","2"),("U2","1"),("C1","2"),("C2","2"),
    ("D1","1"),("U3","1"),("C7","2"),("C5","2"),("U1","1"),("U1","15"),("U1","38"),("U1","39"),("C3","2"),("C4","2"),("C6","2"),
    ("SW1",s1b.number),("SW2",s2b.number),("J2","16"),("J3","1"),("J3","16"),("D2","1"),("J4","4"),("J5","1"))
net("CC1", ("J1","A5"),("R1","1")); net("CC2", ("J1","B5"),("R2","1"))
net("USB_D-", ("J1","A7"),("J1","B7"),("U3","6")); net("USB_D+", ("J1","A6"),("J1","B6"),("U3","5"))
net("RXD0", ("U3","2"),("U1","34"),("J3","5")); net("TXD0", ("U3","3"),("U1","35"),("J3","4"))
net("DTR", ("U3","13"),("R3","1"),("Q2","2")); net("RTS", ("U3","14"),("R4","1"),("Q1","2"))
net("Q1B", ("R3","2"),("Q1","1")); net("Q2B", ("R4","2"),("Q2","1"))
net("EN", ("Q1","3"),("U1","3"),("R5","2"),("C6","1"),("SW1",s1t.number),("J2","2"))
net("IO0", ("Q2","3"),("U1","25"),("R6","2"),("SW2",s2t.number),("J3","13"))
net("LEDP", ("R7","2"),("D1","2")); net("LEDU", ("R8","2"),("D2","2"))
net("IO2", ("U1","24"),("R8","1"),("J3","14"))
net("IO4", ("U1","26"),("J3","12"),("J5","2"),("R11","2"))
net("IO21", ("U1","33"),("J3","6"))
net("IO22", ("U1","36"),("J3","3"),("J4","3"),("R10","2"))
net("IO23", ("U1","37"),("J3","2"),("J4","2"),("R9","2"))
net("SVP", ("U1","4"),("J2","3")); net("SVN", ("U1","5"),("J2","4"))
simple = {"IO34":(6,"J2",5),"IO35":(7,"J2",6),"IO32":(8,"J2",7),"IO33":(9,"J2",8),"IO25":(10,"J2",9),"IO26":(11,"J2",10),
          "IO27":(12,"J2",11),"IO14":(13,"J2",12),"IO12":(14,"J2",13),"IO13":(16,"J2",14),
          "IO19":(31,"J3",7),"IO18":(30,"J3",8),"IO5":(29,"J3",9),"IO17":(28,"J3",10),
          "IO16":(27,"J3",11),"IO15":(23,"J3",15)}
for nm, (upin, j, jp) in simple.items():
    net(nm, ("U1", str(upin)), (j, str(jp)))

for ref, pins in (("J1", ("A8","B8")), ("U1", ("17","18","19","20","21","22","32")), ("U3", ("7","8","9","10","11","12","15"))):
    for pn in pins: net(f"NC_{ref}_{pn}", (ref, pn))
probs = sh.check()
print("check:", probs if probs else "clean")
ok = sh.verify_against(T)
print("verify:", ok)
if len(sys.argv) > 1:
    import json, os
    sh.emit(sys.argv[1]); print("emitted", sys.argv[1])
    pro = os.path.splitext(sys.argv[1])[0] + ".kicad_pro"
    assert os.path.exists(pro), "project file missing -- restore it, do not regenerate it"
